### PR TITLE
Line break fix

### PR DESCRIPTION
**Pull request by SunboX**
This fixes issue #4

### CODE REVIEW

**Comment by honzajavorek** [comment]
Hi @SunboX, thanks for the contribution! I'm sorry it took us so long to look at this. That won't happen again!

Do you think we could solve this with following?

```js
.split(/\r?\n/)
```

**Comment by SunboX** [comment]
Hi, don't know. It's some time now. ;) But the related issue has a test case referenced. So you should be able to try it out. I'm sadly haven't the time right now.

**Comment by roccomuso** [comment]
+1

**Comment by honzajavorek** [comment]
@roccomuso Would you be willing to send an equivalent PR with my comment about `.split(/\r?\n/)` addressed?

**Comment by roccomuso** [comment]
OK, also found a [typo](https://github.com/apiaryio/http-string-parser/blob/master/test/unit/parser-test.coffee#L26) in a test.

**Comment by honzajavorek** [comment]
Closed by #7.

**Pull request closed without merging**
